In [2]:
# Import necessary modules
import pandas as pd
import numpy as np
import difflib

def within_range(checknumber, range_start, range_end):
    """" 
    Function to check if a BGB booking year falls within the timespan
    in DAS referred to in the introduction to this script
    
    """
    if (checknumber >= range_start) & (checknumber <= (range_end + 20)):
        return True
    else:
        return False

In [3]:
# First, load the entire Zeemonsterrollen database
gzm = pd.ExcelFile('zeemonsterrollen.xlsx')

# Load the match list between BGB and DAS
bgbmatch = pd.ExcelFile('Matching_results.xlsx')

In [4]:
# Parse the Excel sheets we will be using
zeemons = gzm.parse('Database GZM (MvR 2014)')
zeemons = zeemons.set_index('ID')

bgbnomatch = bgbmatch.parse('No match')

In [5]:
# Loop over all entries without a corresponding DAS Ship ID

gzm_ships = []

for entry in zeemons[zeemons['DAS SHIP ID'].isna()].index:
    jaar = zeemons.loc[entry, 'JAAR']
    shipname = zeemons.loc[entry, 'NAAM SCHIP (GESTANDAARDISEERD)']
    this_entry = [jaar, shipname]
    gzm_ships.append(this_entry)


fulldata = pd.DataFrame.from_records(gzm_ships, columns=['Year', 'Shipname'])

In [6]:
fulldata

      Year          Shipname
0     1691     SINT NICOLAAS
1     1691        GRIJPVOGEL
2     1691           BATAVIA
3     1691   STANDVASTIGHEID
4     1691       WIJK OP ZEE
...    ...               ...
1707  1790            TRITON
1708  1790          AFRIKAAN
1709  1791        ORANJEBOOM
1710  1791  CORNELIA ADRIANA
1711  1791        CONSTANTIA

[1712 rows x 2 columns]

In [7]:
summary = fulldata.groupby('Shipname')['Year'].agg({'min', 'max'}).reset_index()
summary['Shipname'] = summary['Shipname'].str.lower()
summary

          Shipname   min   max
0       aardenhout  1696  1706
1         achilles  1714  1719
2             adam  1712  1719
3      adam en eva  1718  1718
4          adriana  1736  1754
..             ...   ...   ...
398      zwaardvis  1697  1708
399   zwarte arend  1696  1696
400        zwerver  1732  1741
401  [eiland edam]  1703  1703
402     [onbekend]  1696  1747

[403 rows x 3 columns]

In [8]:
gzm_shiplist = list(summary['Shipname'].unique())
gzm_shiplist.remove('[onbekend]')

In [9]:
bgbnomatch['BGB ship name'] = bgbnomatch['BGB ship name'].str.lower()

In [10]:
bgbnomatch

,Unnamed: 0,BGB Shipvoyage ID,BGB Voyage ID,BGB ship ID,BGB ship name,BGB Booking year
0,0,139,99448,3150,kleine pallas,1790
1,1,145,99454,3153,langmoedigheid,1790
2,2,149,99458,3154,vredelief,1790
3,3,151,99460,3155,wilhelmina,1790
4,4,153,99462,3156,jonge wilhelmina,1790
...,...,...,...,...,...,...
3983,3983,20338,116787,3412,onbekend,1731
3984,3984,20339,117012,3412,onbekend,1723
3985,3985,20340,117815,3412,onbekend,1729
3986,3986,20341,117832,3412,onbekend,1729
3987,3987,20342,117835,3412,onbekend,1729

In [11]:
counter = 0

for entry in bgbnomatch.index:
    bgbyear = int(bgbnomatch.loc[entry, 'BGB Booking year'])
    bgb_shipname = bgbnomatch.loc[entry, 'BGB ship name']
    checking = difflib.get_close_matches(bgb_shipname, gzm_shiplist, n=3, cutoff=0.85)
    
    if checking:
        try:
            minyear_gzb = int(summary.loc[summary['Shipname'] == bgb_shipname]['min'])
        except:
            minyear_gzb = 0
        
        try:
            maxyear_gzb = int(summary.loc[summary['Shipname'] == bgb_shipname]['max'])
        except:
            maxyear_gzb = 0

        
        if within_range(bgbyear, minyear_gzb, maxyear_gzb):
            counter += 1
            print(counter)
            print(bgb_shipname)
            print([checking[0]])
            print(bgbyear)
            print(minyear_gzb, maxyear_gzb)
            print('-------------')

1
kleine pallas
['kleine pallas']
1790
1779 1790
-------------
2
cornelia adriana
['cornelia adriana']
1780
1778 1791
-------------
3
cornelia adriana
['cornelia adriana']
1780
1778 1791
-------------
4
kleine pallas
['kleine pallas']
1780
1779 1790
-------------
5
kleine pallas
['kleine pallas']
1790
1779 1790
-------------
6
rembang
['rembang']
1790
1714 1789
-------------
7
kleine pallas
['kleine pallas']
1787
1779 1790
-------------
8
kleine pallas
['kleine pallas']
1787
1779 1790
-------------
9
kleine pallas
['kleine pallas']
1787
1779 1790
-------------
10
charlotta christina
['charlotte christina']
0
0 0
-------------
11
cornelia adriana
['cornelia adriana']
1780
1778 1791
-------------
12
kleine pallas
['kleine pallas']
1780
1779 1790
-------------
13
rembang
['rembang']
1787
1714 1789
-------------
14
cornelia adriana
['cornelia adriana']
1787
1778 1791
-------------
15
kleine pallas
['kleine pallas']
1787
1779 1790
-------------
16
kleine pallas
['kleine pallas']
1787
1779 1790
-------------
17
cornelia adriana
['cornelia adriana']
1783
1778 1791
-------------
18
cornelia adriana
['cornelia adriana']
1783
1778 1791
-------------
19
kleine pallas
['kleine pallas']
1783
1779 1790
-------------
20
cornelia adriana
['cornelia adriana']
1785
1778 1791
-------------
21
kleine pallas
['kleine pallas']
1785
1779 1790
-------------
22
kleine pallas
['kleine pallas']
1785
1779 1790
-------------
23
postiljon
['postiljon']
1783
1755 1782
-------------
24
cornelia adriana
['cornelia adriana']
1785
1778 1791
-------------
25
cornelia adriana
['cornelia adriana']
1785
1778 1791
-------------
26
kleine pallas
['kleine pallas']
1785
1779 1790
-------------
27
kleine pallas
['kleine pallas']
1782
1779 1790
-------------
28
cornelia adriana
['cornelia adriana']
1782
1778 1791
-------------
29
postiljon
['postiljon']
1801
1755 1782
-------------
30
postiljon
['postiljon']
1801
1755 1782
-------------
31
cornelia adriana
['cornelia adriana']
1782
1778 1791
-------------
32
rembang
['rembang']
1801
1714 1789
-------------
33
geertruida susanna
['geertruida susanna']
1780
1768 1782
-------------
34
kleine pallas
['kleine pallas']
1781
1779 1790
-------------
35
rembang
['rembang']
1790
1714 1789
-------------
36
cornelia adriana
['cornelia adriana']
1781
1778 1791
-------------
37
geertruida susanna
['geertruida susanna']
1778
1768 1782
-------------
38
cornelia adriana
['cornelia adriana']
1778
1778 1791
-------------
39
cornelia adriana
['cornelia adriana']
1778
1778 1791
-------------
40
jonge petrus albertus
['jonge petrus albertus']
1778
1773 1779
-------------
41
jonge petrus albertus
['jonge petrus albertus']
1778
1773 1779
-------------
42
geertruida susanna
['geertruida susanna']
1778
1768 1782
-------------
43
cornelia adriana
['cornelia adriana']
1778
1778 1791
-------------
44
cornelia adriana
['cornelia adriana']
1778
1778 1791
-------------
45
jonge petrus albertus
['jonge petrus albertus']
1778
1773 1779
-------------
46
jonge petrus albertus
['jonge petrus albertus']
1778
1773 1779
-------------
47
postiljon
['postiljon']
1801
1755 1782
-------------
48
jonge petrus albertus
['jonge petrus albertus']
1776
1773 1779
-------------
49
postiljon
['postiljon']
1801
1755 1782
-------------
50
jonge petrus albertus
['jonge petrus albertus']
1776
1773 1779
-------------
51
geertruida susanna
['geertruida susanna']
1777
1768 1782
-------------
52
jonge petrus albertus
['jonge petrus albertus']
1777
1773 1779
-------------
53
jonge petrus albertus
['jonge petrus albertus']
1777
1773 1779
-------------
54
colombo
['colombo']
1776
1717 1762
-------------
55
schildpad
['schildpad']
1776
1760 1760
-------------
56
colombo
['colombo']
1776
1717 1762
-------------
57
geertruida susanna
['geertruida susanna']
1777
1768 1782
-------------
58
jonge petrus albertus
['jonge petrus albertus']
1777
1773 1779
-------------
59
jonge petrus albertus
['jonge petrus albertus']
1775
1773 1779
-------------
60
schildpad
['schildpad']
1777
1760 1760
-------------
61
schildpad
['schildpad']
1777
1760 1760
-------------
62
geertruida susanna
['geertruida susanna']
1775
1768 1782
-------------
63
jonge petrus albertus
['jonge petrus albertus']
1775
1773 1779
-------------
64
geertruida susanna
['geertruida susanna']
1772
1768 1782
-------------
65
sukkelaar
['sukkelaar']
1772
1772 1772
-------------
66
adriana
['adriana']
1772
1736 1754
-------------
67
adriana
['adriana']
1772
1736 1754
-------------
68
adriana
['adriana']
1769
1736 1754
-------------
69
adriana
['adriana']
1769
1736 1754
-------------
70
schildpad
['schildpad']
1775
1760 1760
-------------
71
gale
['galei']
0
0 0
-------------
72
geertruida susanna
['geertruida susanna']
1772
1768 1782
-------------
73
adriana
['adriana']
1769
1736 1754
-------------
74
adriana
['adriana']
1767
1736 1754
-------------
75
geertruida susanna
['geertruida susanna']
1772
1768 1782
-------------
76
sukkelaar
['sukkelaar']
1772
1772 1772
-------------
77
geertruida susanna
['geertruida susanna']
1772
1768 1782
-------------
78
adriana
['adriana']
1772
1736 1754
-------------
79
adriana
['adriana']
1772
1736 1754
-------------
80
adriana
['adriana']
1772
1736 1754
-------------
81
parelmoer
['parelmoer']
1764
1759 1759
-------------
82
adriana
['adriana']
1766
1736 1754
-------------
83
adriana
['adriana']
1764
1736 1754
-------------
84
meeuw
['meeuw']
1766
1743 1757
-------------
85
adriana
['adriana']
1766
1736 1754
-------------
86
cornelia adriana
['cornelia adriana']
1779
1778 1791
-------------
87
cornelia adriana
['cornelia adriana']
1779
1778 1791
-------------
88
jonge petrus albertus
['jonge petrus albertus']
1779
1773 1779
-------------
89
cornelia adriana
['cornelia adriana']
1779
1778 1791
-------------
90
cornelia adriana
['cornelia adriana']
1779
1778 1791
-------------
91
cornelia adriana
['cornelia adriana']
1779
1778 1791
-------------
92
meeuw
['meeuw']
1766
1743 1757
-------------
93
anthonia dorothea
['anthonia dorothea']
1764
1745 1746
-------------
94
anthonia dorothea
['anthonia dorothea']
1764
1745 1746
-------------
95
schildpad
['schildpad']
1764
1760 1760
-------------
96
leguaan
['leguaan']
1763
1762 1762
-------------
97
vliegende vis
['vliegende vis']
1762
1754 1756
-------------
98
adriana
['adriana']
1763
1736 1754
-------------
99
adriana
['adriana']
1763
1736 1754
-------------
100
geertruida susanna
['geertruida susanna']
1773
1768 1782
-------------
101
geertruida susanna
['geertruida susanna']
1773
1768 1782
-------------
102
jonge petrus albertus
['jonge petrus albertus']
1773
1773 1779
-------------
103
adriana
['adriana']
1773
1736 1754
-------------
104
vliegende vis
['vliegende vis']
1773
1754 1756
-------------
105
colombo
['colombo']
1762
1717 1762
-------------
106
anthonia dorothea
['anthonia dorothea']
1763
1745 1746
-------------
107
anthonia dorothea
['anthonia dorothea']
1763
1745 1746
-------------
108
schildpad
['schildpad']
1763
1760 1760
-------------
109
schildpad
['schildpad']
1763
1760 1760
-------------
110
schildpad
['schildpad']
1763
1760 1760
-------------
111
geertruida susanna
['geertruida susanna']
1773
1768 1782
-------------
112
vliegende vis
['vliegende vis']
1763
1754 1756
-------------
113
adriana
['adriana']
1773
1736 1754
-------------
114
vliegende vis
['vliegende vis']
1762
1754 1756
-------------
115
adriana
['adriana']
1762
1736 1754
-------------
116
anthonia dorothea
['anthonia dorothea']
1762
1745 1746
-------------
117
anthonia dorothea
['anthonia dorothea']
1762
1745 1746
-------------
118
anthonia dorothea
['anthonia dorothea']
1762
1745 1746
-------------
119
schildpad
['schildpad']
1762
1760 1760
-------------
120
wereld
['wereld']
1760
1751 1758
-------------
121
rijder
['rijder']
1760
1758 1760
-------------
122
vliegende vis
['vliegende vis']
1760
1754 1756
-------------
123
kleine julius
['kleine julius']
1762
1754 1754
-------------
124
schildpad
['schildpad']
1760
1760 1760
-------------
125
anthonia dorothea
['anthonia dorothea']
1762
1745 1746
-------------
126
anthonia dorothea
['anthonia dorothea']
1762
1745 1746
-------------
127
anthonia dorothea
['anthonia dorothea']
1762
1745 1746
-------------
128
rijder
['rijder']
1761
1758 1760
-------------
129
wereld
['wereld']
1761
1751 1758
-------------
130
wereld
['wereld']
1761
1751 1758
-------------
131
wereld
['wereld']
1761
1751 1758
-------------
132
schildpad
['schildpad']
1761
1760 1760
-------------

133
rijder
['rijder']
1761
1758 1760
-------------
134
schildpad
['schildpad']
1761
1760 1760
-------------
135
rijder
['rijder']
1760
1758 1760
-------------
136
schildpad
['schildpad']
1760
1760 1760
-------------
137
anthonia dorothea
['anthonia dorothea']
1760
1745 1746
-------------
138
rijder
['rijder']
1761
1758 1760
-------------
139
wereld
['wereld']
1760
1751 1758
-------------
140
wereld
['wereld']
1757
1751 1758
-------------
141
schildpad
['schildpad']
1761
1760 1760
-------------
142
postiljon
['postiljon']
1761
1755 1782
-------------
143
aurora
['aurora']
1757
1756 1756
-------------
144
schildpad
['schildpad']
1761
1760 1760
-------------
145
rijder
['rijder']
1761
1758 1760
-------------
146
anthonia dorothea
['anthonia dorothea']
1761
1745 1746
-------------
147
wereld
['wereld']
1757
1751 1758
-------------
148
aletta adriana
['aletta adriana']
1761
1754 1754
-------------
149
anthonia dorothea
['anthonia dorothea']
1761
1745 1746
-------------
150
rijder
['rijder']
1759
1758 1760
-------------
151
ongehoorzaamheid
['ongehoorzaamheid']
1759
1742 1744
-------------
152
kaaskooper
['kaaskoper']
0
0 0
-------------
153
wereld
['wereld']
1759
1751 1758
-------------
154
meeuw
['meeuw']
1757
1743 1757
-------------
155
rijder
['rijder']
1759
1758 1760
-------------
156
adriana
['adriana']
1751
1736 1754
-------------
157
hervatting
['hervatting']
1751
1746 1752
-------------
158
ongehoorzaamheid
['ongehoorzaamheid']
1743
1742 1744
-------------
159
lamatjang
['lamatjang']
1743
1739 1739
-------------
160
anthonia
['anthonia']
1743
1725 1744
-------------
161
anthonia
['anthonia']
1743
1725 1744
-------------
162
adriana
['adriana']
1751
1736 1754
-------------
163
geertruida maria
['geertruida maria']
1743
1731 1752
-------------
164
verlangen
['verlangen']
1743
1735 1736
-------------
165
verlangen
['verlangen']
1743
1735 1736
-------------
166
wereld
['wereld']
1757
1751 1758
-------------
167
wereld
['wereld']
1757
1751 1758
-------------
168
wereld
['wereld']
1757
1751 1758
-------------
169
nederlandse maagd
['nederlandse maagd']
1751
1747 1761
-------------
170
herderin
['herderin']
1757
1698 1755
-------------
171
aurora
['aurora']
1757
1756 1756
-------------
172
anthonia dorothea
['anthonia dorothea']
1757
1745 1746
-------------
173
wereld
['wereld']
1751
1751 1758
-------------
174
wereld
['wereld']
1759
1751 1758
-------------
175
wereld
['wereld']
1757
1751 1758
-------------
176
adriana
['adriana']
1751
1736 1754
-------------
177
ongehoorzaamheid
['ongehoorzaamheid']
1751
1742 1744
-------------
178
galathea
['galathea']
1751
1746 1752
-------------
179
herderin
['herderin']
1757
1698 1755
-------------
180
nederlandse maagd
['nederlandse maagd']
1751
1747 1761
-------------
181
anthonia dorothea
['anthonia dorothea']
1759
1745 1746
-------------
182
anthonia dorothea
['anthonia dorothea']
1759
1745 1746
-------------
183
anthonia dorothea
['anthonia dorothea']
1751
1745 1746
-------------
184
herderin
['herderin']
1759
1698 1755
-------------
185
anthonia dorothea
['anthonia dorothea']
1759
1745 1746
-------------
186
anthonia dorothea
['anthonia dorothea']
1751
1745 1746
-------------
187
olijftak
['olijftak']
1743
1728 1729
-------------
188
pepertuin
['pepertuin']
1702
1693 1746
-------------
189
andromeda
['andromeda']
1702
1694 1710
-------------
190
doradus
['doradus']
1702
1696 1697
-------------
191
pepertuin
['pepertuin']
1751
1693 1746
-------------
192
meeuw
['meeuw']
1751
1743 1757
-------------
193
pepertuin
['pepertuin']
1751
1693 1746
-------------
194
galathea
['galathea']
1751
1746 1752
-------------
195
geertruida susanna
['geertruida susanna']
1774
1768 1782
-------------
196
jonge petrus albertus
['jonge petrus albertus']
1774
1773 1779
-------------
197
jonge petrus albertus
['jonge petrus albertus']
1774
1773 1779
-------------
198
adriana
['adriana']
1774
1736 1754
-------------
199
adriana
['adriana']
1774
1736 1754
-------------
200
adriana
['adriana']
1774
1736 1754
-------------
201
adriana
['adriana']
1754
1736 1754
-------------
202
wereld
['wereld']
1754
1751 1758
-------------
203
rembang
['rembang']
1754
1714 1789
-------------
204
adriana
['adriana']
1774
1736 1754
-------------
205
andromeda
['andromeda']
1702
1694 1710
-------------
206
overmaas
['overmaas']
1754
1750 1750
-------------
207
doradus
['doradus']
1702
1696 1697
-------------
208
adriana
['adriana']
1754
1736 1754
-------------
209
waijer
['waijer']
1702
1697 1714
-------------
210
wereld
['wereld']
1755
1751 1758
-------------
211
wereld
['wereld']
1755
1751 1758
-------------
212
pepertuin
['pepertuin']
1702
1693 1746
-------------
213
doradus
['doradus']
1702
1696 1697
-------------
214
wereld
['wereld']
1755
1751 1758
-------------
215
pepertuin
['pepertuin']
1755
1693 1746
-------------
216
adriana
['adriana']
1755
1736 1754
-------------
217
adriana
['adriana']
1755
1736 1754
-------------
218
goa
['goa']
1702
1699 1712
-------------
219
andromeda
['andromeda']
1702
1694 1710
-------------
220
anthonia dorothea
['anthonia dorothea']
1754
1745 1746
-------------
221
anthonia dorothea
['anthonia dorothea']
1754
1745 1746
-------------
222
aletta adriana
['aletta adriana']
1754
1754 1754
-------------
223
anthonia dorothea
['anthonia dorothea']
1754
1745 1746
-------------
224
anthonia dorothea
['anthonia dorothea']
1754
1745 1746
-------------
225
vliegende vis
['vliegende vis']
1754
1754 1756
-------------
226
anthonia dorothea
['anthonia dorothea']
1754
1745 1746
-------------
227
anthonia dorothea
['anthonia dorothea']
1754
1745 1746
-------------
228
wereld
['wereld']
1755
1751 1758
-------------
229
adriana
['adriana']
1754
1736 1754
-------------
230
herderin
['herderin']
1755
1698 1755
-------------
231
postiljon
['postiljon']
1755
1755 1782
-------------
232
wereld
['wereld']
1755
1751 1758
-------------
233
wereld
['wereld']
1752
1751 1758
-------------
234
wereld
['wereld']
1752
1751 1758
-------------
235
adriana
['adriana']
1752
1736 1754
-------------
236
ongehoorzaamheid
['ongehoorzaamheid']
1752
1742 1744
-------------
237
pepertuin
['pepertuin']
1752
1693 1746
-------------
238
lijdzaamheid
['lijdzaamheid']
1752
1734 1753
-------------
239
galathea
['galathea']
1752
1746 1752
-------------
240
galathea
['galathea']
1752
1746 1752
-------------
241
galathea
['galathea']
1752
1746 1752
-------------
242
wereld
['wereld']
1755
1751 1758
-------------
243
anthonia dorothea
['anthonia dorothea']
1755
1745 1746
-------------
244
neira
['neira']
1702
1701 1711
-------------
245
oostvoorn
['oostvoorn']
1702
1699 1708
-------------
246
aardenhout
['aardenhout']
1702
1696 1706
-------------
247
pepertuin
['pepertuin']
1702
1693 1746
-------------
248
wereld
['wereld']
1752
1751 1758
-------------
249
lijdzaamheid
['lijdzaamheid']
1752
1734 1753
-------------
250
galathea
['galathea']
1752
1746 1752
-------------
251
adriana
['adriana']
1753
1736 1754
-------------
252
wereld
['wereld']
1753
1751 1758
-------------
253
wereld
['wereld']
1753
1751 1758
-------------
254
adriana
['adriana']
1753
1736 1754
-------------
255
pepertuin
['pepertuin']
1753
1693 1746
-------------
256
lijdzaamheid
['lijdzaamheid']
1753
1734 1753
-------------
257
lijdzaamheid
['lijdzaamheid']
1753
1734 1753
-------------
258
anthonia dorothea
['anthonia dorothea']
1752
1745 1746
-------------
259
anthonia dorothea
['anthonia dorothea']
1752
1745 1746
-------------
260
olijftak
['olijftak']
1742
1728 1729
-------------
261
rotte
['rotte']
1742
1736 1741
-------------
262
wereld
['wereld']
1753
1751 1758
-------------
263
sousang
['sousang']
1742
1712 1723
-------------
264
goa
['goa']
1702
1699 1712
-------------
265
olijftak
['olijftak']
1742
1728 1729
-------------
266
anthonia
['anthonia']
1741
1725 1744
-------------
267
ongehoorzaamheid
['ongehoorzaamheid']
1742
1742 1744
-------------
268
anthonia dorothea
['anthonia dorothea']
1753
1745 1746
-------------
269
anthonia dorothea
['anthonia dorothea']
1753
1745 1746
-------------
270
anthonia dorothea
['anthonia dorothea']
1753
1745 1746
-------------
271
anthonia
['anthonia']
1741
1725 1744
-------------
272
olijftak
['olijftak']
1742
1728 1729
-------------
273
onbeschaamdheid
['onbeschaamdheid']
1742
1733 1733
-------------
274
pepertuin
['pepertuin']
1742
1693 1746
-------------
275
pepertuin
['pepertuin']
1742
1693 1746
-------------
276
pepertuin
['pepertuin']
1742
1693 1746
-------------
277
olijftak
['olijftak']
1742
1728 1729
-------------
278
colombo
['colombo']
1742
1717 1762
-------------
279
lijdzaamheid
['lijdzaamheid']
1742
1734 1753
-------------
280
geertruida maria
['geertruida maria']
1742
1731 1752
-------------
281
geertruida maria
['geertruida maria']
1742
1731 1752
-------------
282
adriana
['adriana']
1742
1736 1754
-------------
283
adriana
['adriana']
1742
1736 1754
-------------
284
adriana
['adriana']
1742
1736 1754
-------------
285
adriana
['adriana']
1742
1736 1754
-------------
286
geertruida maria
['geertruida maria']
1742
1731 1752
-------------
287
anthonia
['anthonia']
1741
1725 1744
-------------
288
lamatjang
['lamatjang']
1742
1739 1739
-------------
289
andromeda
['andromeda']
1702
1694 1710
-------------
290
oostvoorn
['oostvoorn']
1702
1699 1708
-------------
291
adriana
['adriana']
1753
1736 1754
-------------
292
ongehoorzaamheid
['ongehoorzaamheid']
1753
1742 1744
-------------
293
meeuw
['meeuw']
1753
1743 1757
-------------
294
ongehoorzaamheid
['ongehoorzaamheid']
1753
1742 1744
-------------
295
ongehoorzaamheid
['ongehoorzaamheid']
1742
1742 1744
-------------
296
jacob willem
['jacob willem']
1741
1736 1741
-------------
297
anthonia
['anthonia']
1741
1725 1744
-------------
298
rotte
['rotte']
1741
1736 1741
-------------
299
pepertuin
['pepertuin']
1741
1693 1746
-------------
300
anthonia
['anthonia']
1741
1725 1744
-------------
301
andromeda
['andromeda']
1703
1694 1710
-------------
302
oostvoorn
['oostvoorn']
1703
1699 1708
-------------
303
oostvoorn
['oostvoorn']
1703
1699 1708
-------------
304
goa
['goa']
1703
1699 1712
-------------
305
pepertuin
['pepertuin']
1703
1693 1746
-------------
306
waijer
['waijer']
1703
1697 1714
-------------
307
herderin
['herderin']

1703
1698 1755
-------------
308
pepertuin
['pepertuin']
1703
1693 1746
-------------
309
pepertuin
['pepertuin']
1703
1693 1746
-------------
310
onbeschaamdheid
['onbeschaamdheid']
1739
1733 1733
-------------
311
geertruida maria
['geertruida maria']
1738
1731 1752
-------------
312
sousang
['sousang']
1738
1712 1723
-------------
313
bouro
['bouro']
1738
1712 1719
-------------
314
jacob willem
['jacob willem']
1738
1736 1741
-------------
315
snip
['snip']
1732
1729 1736
-------------
316
jacob willem
['jacob willem']
1739
1736 1741
-------------
317
jonge dirk
['jonge dirk']
1739
1739 1739
-------------
318
lamatjang
['lamatjang']
1739
1739 1739
-------------
319
verlangen
['verlangen']
1739
1735 1736
-------------
320
sousang
['sousang']
1735
1712 1723
-------------
321
goudmijn
['goudmijn']
1735
1734 1734
-------------
322
snip
['snip']
1732
1729 1736
-------------
323
beschermer
['beschermer']
1732
1709 1734
-------------
324
beschermer
['beschermer']
1732
1709 1734
-------------
325
beschermer
['beschermer']
1732
1709 1734
-------------
326
langerak
['langerak']
1732
1713 1735
-------------
327
geertruida maria
['geertruida maria']
1738
1731 1752
-------------
328
adriana
['adriana']
1738
1736 1754
-------------
329
goudmijn
['goudmijn']
1738
1734 1734
-------------
330
onbeschaamdheid
['onbeschaamdheid']
1738
1733 1733
-------------
331
casuaris
['casuaris']
1735
1703 1719
-------------
332
beschermer
['beschermer']
1735
1709 1734
-------------
333
beschermer
['beschermer']
1735
1709 1734
-------------
334
verlangen
['verlangen']
1735
1735 1736
-------------
335
beschermer
['beschermer']
1735
1709 1734
-------------
336
jacob willem
['jacob willem']
1739
1736 1741
-------------
337
lijdzaamheid
['lijdzaamheid']
1739
1734 1753
-------------
338
hottentot
['hottentot']
1739
1719 1726
-------------
339
adriana
['adriana']
1739
1736 1754
-------------
340
anthonia
['anthonia']
1739
1725 1744
-------------
341
colombo
['colombo']
1739
1717 1762
-------------
342
jacob willem
['jacob willem']
1738
1736 1741
-------------
343
colombo
['colombo']
1738
1717 1762
-------------
344
hottentot
['hottentot']
1738
1719 1726
-------------
345
lijdzaamheid
['lijdzaamheid']
1738
1734 1753
-------------
346
lijdzaamheid
['lijdzaamheid']
1738
1734 1753
-------------
347
colombo
['colombo']
1738
1717 1762
-------------
348
olijftak
['olijftak']
1738
1728 1729
-------------
349
olijftak
['olijftak']
1738
1728 1729
-------------
350
jacob willem
['jacob willem']
1738
1736 1741
-------------
351
beschermer
['beschermer']
1732
1709 1734
-------------
352
suikermaalder
['suikermaalder']
1732
1711 1754
-------------
353
beschermer
['beschermer']
1732
1709 1734
-------------
354
noodhulp
['noodhulp']
1732
1712 1718
-------------
355
dwars in de weg
['dwars in de weg']
1732
1709 1713
-------------
356
rotte
['rotte']
1739
1736 1741
-------------
357
olijftak
['olijftak']
1739
1728 1729
-------------
358
olijftak
['olijftak']
1739
1728 1729
-------------
359
jacob willem
['jacob willem']
1739
1736 1741
-------------
360
hottentot
['hottentot']
1739
1719 1726
-------------
361
adriana
['adriana']
1739
1736 1754
-------------
362
anthonia
['anthonia']
1739
1725 1744
-------------
363
adriana
['adriana']
1739
1736 1754
-------------
364
anthonia
['anthonia']
1739
1725 1744
-------------
365
olijftak
['olijftak']
1732
1728 1729
-------------
366
bouro
['bouro']
1732
1712 1719
-------------
367
olijftak
['olijftak']
1732
1728 1729
-------------
368
olijftak
['olijftak']
1735
1728 1729
-------------
369
olijftak
['olijftak']
1735
1728 1729
-------------
370
bouro
['bouro']
1735
1712 1719
-------------
371
baros
['baros']
1703
1696 1697
-------------
372
tienhoven
['tienhoven']
1724
1723 1729
-------------
373
tienhoven
['tienhoven']
1724
1723 1729
-------------
374
padang
['padang']
1701
1696 1697
-------------
375
pepertuin
['pepertuin']
1701
1693 1746
-------------
376
herderin
['herderin']
1701
1698 1755
-------------
377
herderin
['herderin']
1701
1698 1755
-------------
378
aardenhout
['aardenhout']
1701
1696 1706
-------------
379
herderin
['herderin']
1701
1698 1755
-------------
380
sousang
['sousang']
1724
1712 1723
-------------
381
bouro
['bouro']
1724
1712 1719
-------------
382
andromeda
['andromeda']
1711
1694 1710
-------------
383
andromeda
['andromeda']
1711
1694 1710
-------------
384
neira
['neira']
1711
1701 1711
-------------
385
salpeterzoeker
['salpeterzoeker']
1711
1710 1712
-------------
386
beschermer
['beschermer']
1724
1709 1734
-------------
387
waijer
['waijer']
1711
1697 1714
-------------
388
beschermer
['beschermer']
1724
1709 1734
-------------
389
goa
['goa']
1711
1699 1712
-------------
390
beschermer
['beschermer']
1724
1709 1734
-------------
391
beschermer
['beschermer']
1724
1709 1734
-------------
392
ceram
['ceram']
1711
1697 1713
-------------
393
pepertuin
['pepertuin']
1704
1693 1746
-------------
394
oostvoorn
['oostvoorn']
1704
1699 1708
-------------
395
ceram
['ceram']
1704
1697 1713
-------------
396
andromeda
['andromeda']
1704
1694 1710
-------------
397
aardenhout
['aardenhout']
1704
1696 1706
-------------
398
doradus
['doradus']
1704
1696 1697
-------------
399
ceram
['ceram']
1704
1697 1713
-------------
400
andromeda
['andromeda']
1701
1694 1710
-------------
401
herderin
['herderin']
1701
1698 1755
-------------
402
pepertuin
['pepertuin']
1701
1693 1746
-------------
403
herderin
['herderin']
1701
1698 1755
-------------
404
aardenhout
['aardenhout']
1701
1696 1706
-------------
405
neira
['neira']
1701
1701 1711
-------------
406
aardenhout
['aardenhout']
1701
1696 1706
-------------
407
neira
['neira']
1711
1701 1711
-------------
408
sousang
['sousang']
1724
1712 1723
-------------
409
pepertuin
['pepertuin']
1703
1693 1746
-------------
410
neira
['neira']
1701
1701 1711
-------------
411
hitoe
['hitoe']
1701
1701 1712
-------------
412
herderin
['herderin']
1701
1698 1755
-------------
413
herderin
['herderin']
1701
1698 1755
-------------
414
aardenhout
['aardenhout']
1701
1696 1706
-------------
415
andromeda
['andromeda']
1711
1694 1710
-------------
416
andromeda
['andromeda']
1701
1694 1710
-------------
417
ceram
['ceram']
1701
1697 1713
-------------
418
andromeda
['andromeda']
1704
1694 1710
-------------
419
aardenhout
['aardenhout']
1701
1696 1706
-------------
420
pepertuin
['pepertuin']
1704
1693 1746
-------------
421
goa
['goa']
1711
1699 1712
-------------
422
ceram
['ceram']
1711
1697 1713
-------------
423
casuaris
['casuaris']
1711
1703 1719
-------------
424
oostvoorn
['oostvoorn']
1703
1699 1708
-------------
425
langerak
['langerak']
1724
1713 1735
-------------
426
andromeda
['andromeda']
1704
1694 1710
-------------
427
herderin
['herderin']
1703
1698 1755
-------------
428
oostvoorn
['oostvoorn']
1704
1699 1708
-------------
429
langerak
['langerak']
1715
1713 1735
-------------
430
rembang
['rembang']
1715
1714 1789
-------------
431
rembang
['rembang']
1715
1714 1789
-------------
432
goa
['goa']
1703
1699 1712
-------------
433
jambij
['jambij']
1715
1712 1719
-------------
434
rembang
['rembang']
1715
1714 1789
-------------
435
dwars in de weg
['dwars in de weg']
1711
1709 1713
-------------
436
landouw
['landouw']
1711
1708 1728
-------------
437
beschermer
['beschermer']
1724
1709 1734
-------------
438
beschermer
['beschermer']
1724
1709 1734
-------------
439
herderin
['herderin']
1703
1698 1755
-------------
440
colombo
['colombo']
1724
1717 1762
-------------
441
tienhoven
['tienhoven']
1724
1723 1729
-------------
442
pepertuin
['pepertuin']
1703
1693 1746
-------------
443
landouw
['landouw']
1724
1708 1728
-------------
444
cananoor
['cananoor']
1724
1719 1723
-------------
445
pepertuin
['pepertuin']
1703
1693 1746
-------------
446
tienhoven
['tienhoven']
1724
1723 1729
-------------
447
bouro
['bouro']
1724
1712 1719
-------------
448
doradus
['doradus']
1704
1696 1697
-------------
449
ceram
['ceram']
1704
1697 1713
-------------
450
ceram
['ceram']
1711
1697 1713
-------------
451
langerak
['langerak']
1724
1713 1735
-------------
452
dwars in de weg
['dwars in de weg']
1724
1709 1713
-------------
453
zeilvis
['zeilvis']
1703
1703 1706
-------------
454
sousang
['sousang']
1712
1712 1723
-------------
455
sousang
['sousang']
1712
1712 1723
-------------
456
waijer
['waijer']
1712
1697 1714
-------------
457
andromeda
['andromeda']
1704
1694 1710
-------------
458
hitoe
['hitoe']
1704
1701 1712
-------------
459
neira
['neira']
1704
1701 1711
-------------
460
neira
['neira']
1704
1701 1711
-------------

461
waijer
['waijer']
1704
1697 1714
-------------
462
doradus
['doradus']
1704
1696 1697
-------------
463
herderin
['herderin']
1704
1698 1755
-------------
464
beschermer
['beschermer']
1726
1709 1734
-------------
465
beschermer
['beschermer']
1726
1709 1734
-------------
466
tienhoven
['tienhoven']
1726
1723 1729
-------------
467
tienhoven
['tienhoven']
1726
1723 1729
-------------
468
haai
['haai']
1726
1722 1722
-------------
469
neira
['neira']
1703
1701 1711
-------------
470
aardenhout
['aardenhout']
1703
1696 1706
-------------
471
aardenhout
['aardenhout']
1703
1696 1706
-------------
472
andromeda
['andromeda']
1707
1694 1710
-------------
473
pepertuin
['pepertuin']
1707
1693 1746
-------------
474
pepertuin
['pepertuin']
1707
1693 1746
-------------
475
neira
['neira']
1707
1701 1711
-------------
476
cheribon
['cheribon']
1707
1696 1717
-------------
477
waijer
['waijer']
1707
1697 1714
-------------
478
andromeda
['andromeda']
1707
1694 1710
-------------
479
andromeda
['andromeda']
1707
1694 1710
-------------
480
landouw
['landouw']
1712
1708 1728
-------------
481
langerak
['langerak']
1715
1713 1735
-------------
482
pepertuin
['pepertuin']
1707
1693 1746
-------------
483
pepertuin
['pepertuin']
1707
1693 1746
-------------
484
pepertuin
['pepertuin']
1707
1693 1746
-------------
485
dijkveld
['dijkveld']
1712
1705 1705
-------------
486
landouw
['landouw']
1712
1708 1728
-------------
487
neira
['neira']
1707
1701 1711
-------------
488
neira
['neira']
1712
1701 1711
-------------
489
andromeda
['andromeda']
1707
1694 1710
-------------
490
waijer
['waijer']
1713
1697 1714
-------------
491
beschermer
['beschermer']
1713
1709 1734
-------------
492
jambij
['jambij']
1713
1712 1719
-------------
493
leervis
['leenvis']
0
0 0
-------------
494
jambij
['jambij']
1715
1712 1719
-------------
495
dijkveld
['dijkveld']
1707
1705 1705
-------------
496
dijkveld
['dijkveld']
1707
1705 1705
-------------
497
dijkveld
['dijkveld']
1715
1705 1705
-------------
498
dijkveld
['dijkveld']
1707
1705 1705
-------------
499
dijkveld
['dijkveld']
1707
1705 1705
-------------
500
dijkveld
['dijkveld']
1707
1705 1705
-------------
501
herderin
['herderin']
1707
1698 1755
-------------
502
oostvoorn
['oostvoorn']
1707
1699 1708
-------------
503
herderin
['herderin']
1707
1698 1755
-------------
504
oostvoorn
['oostvoorn']
1707
1699 1708
-------------
505
langerak
['langerak']
1713
1713 1735
-------------
506
lijnbaan
['lijnbaan']
1715
1714 1719
-------------
507
lijnbaan
['lijnbaan']
1715
1714 1719
-------------
508
neira
['neira']
1715
1701 1711
-------------
509
jambij
['jambij']
1715
1712 1719
-------------
510
uitgang
['uitgang']
1722
1720 1721
-------------
511
suikermaalder
['suikermaalder']
1722
1711 1754
-------------
512
bouro
['bouro']
1722
1712 1719
-------------
513
bouro
['bouro']
1722
1712 1719
-------------
514
sousouhounang
['sousouhounang']
1722
1705 1719
-------------
515
samarang
['samarang']
1722
1696 1717
-------------
516
beschermer
['beschermer']
1722
1709 1734
-------------
517
beschermer
['beschermer']
1722
1709 1734
-------------
518
beschermer
['beschermer']
1722
1709 1734
-------------
519
suikermaalder
['suikermaalder']
1722
1711 1754
-------------
520
beschermer
['beschermer']
1722
1709 1734
-------------
521
beschermer
['beschermer']
1722
1709 1734
-------------
522
beschermer
['beschermer']
1722
1709 1734
-------------
523
beschermer
['beschermer']
1722
1709 1734
-------------
524
beschermer
['beschermer']
1722
1709 1734
-------------
525
andromeda
['andromeda']
1709
1694 1710
-------------
526
andromeda
['andromeda']
1709
1694 1710
-------------
527
waijer
['waijer']
1709
1697 1714
-------------
528
dijkveld
['dijkveld']
1713
1705 1705
-------------
529
landouw
['landouw']
1713
1708 1728
-------------
530
dijkveld
['dijkveld']
1713
1705 1705
-------------
531
landouw
['landouw']
1713
1708 1728
-------------
532
landouw
['landouw']
1713
1708 1728
-------------
533
landouw
['landouw']
1713
1708 1728
-------------
534
landouw
['landouw']
1713
1708 1728
-------------
535
ceram
['ceram']
1713
1697 1713
-------------
536
beschermer
['beschermer']
1709
1709 1734
-------------
537
andromeda
['andromeda']
1709
1694 1710
-------------
538
uitgang
['uitgang']
1722
1720 1721
-------------
539
langerak
['langerak']
1722
1713 1735
-------------
540
dijkveld
['dijkveld']
1709
1705 1705
-------------
541
dwars in de weg
['dwars in de weg']
1709
1709 1713
-------------
542
landouw
['landouw']
1709
1708 1728
-------------
543
dwars in de weg
['dwars in de weg']
1709
1709 1713
-------------
544
olijftak
['olijftak']
1731
1728 1729
-------------
545
oppas
['oppas']
1731
1715 1719
-------------
546
bergwerker
['bergwerker']
1731
1728 1729
-------------
547
langerak
['langerak']
1731
1713 1735
-------------
548
beschermer
['beschermer']
1722
1709 1734
-------------
549
beschermer
['beschermer']
1722
1709 1734
-------------
550
beschermer
['beschermer']
1722
1709 1734
-------------
551
beschermer
['beschermer']
1722
1709 1734
-------------
552
beschermer
['beschermer']
1722
1709 1734
-------------
553
beschermer
['beschermer']
1722
1709 1734
-------------
554
dijkveld
['dijkveld']
1722
1705 1705
-------------
555
cananoor
['cananoor']
1722
1719 1723
-------------
556
cananoor
['cananoor']
1722
1719 1723
-------------
557
dijkveld
['dijkveld']
1722
1705 1705
-------------
558
landouw
['landouw']
1722
1708 1728
-------------
559
landouw
['landouw']
1722
1708 1728
-------------
560
cananoor
['cananoor']
1722
1719 1723
-------------
561
dijkveld
['dijkveld']
1722
1705 1705
-------------
562
rembang
['rembang']
1722
1714 1789
-------------
563
uitgang
['uitgang']
1722
1720 1721
-------------
564
uitgang
['uitgang']
1722
1720 1721
-------------
565
dijkveld
['dijkveld']
1709
1705 1705
-------------
566
dwars in de weg
['dwars in de weg']
1709
1709 1713
-------------
567
langerak
['langerak']
1722
1713 1735
-------------
568
ceram
['ceram']
1709
1697 1713
-------------
569
beschermer
['beschermer']
1731
1709 1734
-------------
570
langerak
['langerak']
1731
1713 1735
-------------
571
langerak
['langerak']
1731
1713 1735
-------------
572
beschermer
['beschermer']
1731
1709 1734
-------------
573
dwars in de weg
['dwars in de weg']
1731
1709 1713
-------------
574
olijftak
['olijftak']
1731
1728 1729
-------------
575
bouro
['bouro']
1731
1712 1719
-------------
576
olijftak
['olijftak']
1731
1728 1729
-------------
577
lijnbaan
['lijnbaan']
1723
1714 1719
-------------
578
aardenhout
['aardenhout']
1703
1696 1706
-------------
579
langerak
['langerak']
1727
1713 1735
-------------
580
tienhoven
['tienhoven']
1727
1723 1729
-------------
581
langerak
['langerak']
1727
1713 1735
-------------
582
oppas
['oppas']
1723
1715 1719
-------------
583
beschermer
['beschermer']
1723
1709 1734
-------------
584
beschermer
['beschermer']
1723
1709 1734
-------------
585
beschermer
['beschermer']
1723
1709 1734
-------------
586
beschermer
['beschermer']
1723
1709 1734
-------------
587
beschermer
['beschermer']
1723
1709 1734
-------------
588
sumanapper
['sumanapper']
1727
1712 1719
-------------
589
beschermer
['beschermer']
1727
1709 1734
-------------
590
beschermer
['beschermer']
1727
1709 1734
-------------
591
beschermer
['beschermer']
1727
1709 1734
-------------
592
beschermer
['beschermer']
1727
1709 1734
-------------
593
langerak
['langerak']
1731
1713 1735
-------------
594
adriana
['adriana']
1741
1736 1754
-------------
595
adriana
['adriana']
1741
1736 1754
-------------
596
lijdzaamheid
['lijdzaamheid']
1741
1734 1753
-------------
597
sousang
['sousang']
1741
1712 1723
-------------
598
olijftak
['olijftak']
1741
1728 1729
-------------
599
jacob willem
['jacob willem']
1741
1736 1741
-------------
600
tienhoven
['tienhoven']
1727
1723 1729
-------------
601
langerak
['langerak']
1726
1713 1735
-------------
602
beschermer
['beschermer']
1726
1709 1734
-------------
603
langerak
['langerak']
1726
1713 1735
-------------
604
colombo
['colombo']
1726
1717 1762
-------------
605
colombo
['colombo']
1726
1717 1762
-------------
606
dwars in de weg
['dwars in de weg']
1726
1709 1713
-------------
607
cananoor
['cananoor']
1726
1719 1723
-------------
608
colombo
['colombo']
1726
1717 1762
-------------
609
tienhoven
['tienhoven']
1723
1723 1729
-------------
610
bouro
['bouro']
1726
1712 1719
-------------
611
langerak
['langerak']
1726
1713 1735
-------------
612
tienhoven
['tienhoven']
1727
1723 1729
-------------
613
langerak
['langerak']
1727
1713 1735
-------------
614
langerak
['langerak']
1723
1713 1735
-------------
615
beschermer
['beschermer']
1723
1709 1734
-------------
616
beschermer
['beschermer']
1723
1709 1734
-------------
617
langerak
['langerak']
1727
1713 1735
-------------
618
hottentot
['hottentot']
1727
1719 1726
-------------
619
colombo
['colombo']
1727
1717 1762
-------------
620
landouw
['landouw']
1727
1708 1728
-------------
621
bouro
['bouro']
1727
1712 1719
-------------
622
langerak
['langerak']
1727
1713 1735
-------------

623
colombo
['colombo']
1723
1717 1762
-------------
624
colombo
['colombo']
1723
1717 1762
-------------
625
cananoor
['cananoor']
1723
1719 1723
-------------
626
dijkveld
['dijkveld']
1723
1705 1705
-------------
627
tienhoven
['tienhoven']
1723
1723 1729
-------------
628
uitgang
['uitgang']
1723
1720 1721
-------------
629
bouro
['bouro']
1723
1712 1719
-------------
630
bouro
['bouro']
1723
1712 1719
-------------
631
uitgang
['uitgang']
1723
1720 1721
-------------
632
langerak
['langerak']
1723
1713 1735
-------------
633
colombo
['colombo']
1729
1717 1762
-------------
634
snip
['snip']
1729
1729 1736
-------------
635
langerak
['langerak']
1729
1713 1735
-------------
636
olijftak
['olijftak']
1729
1728 1729
-------------
637
bergwerker
['bergwerker']
1729
1728 1729
-------------
638
beschermer
['beschermer']
1729
1709 1734
-------------
639
beschermer
['beschermer']
1729
1709 1734
-------------
640
beschermer
['beschermer']
1729
1709 1734
-------------
641
beschermer
['beschermer']
1729
1709 1734
-------------
642
beschermer
['beschermer']
1729
1709 1734
-------------
643
tienhoven
['tienhoven']
1729
1723 1729
-------------
644
haai
['haai']
1729
1722 1722
-------------
645
snip
['snip']
1729
1729 1736
-------------
646
snip
['snip']
1729
1729 1736
-------------
647
suikermaalder
['suikermaalder']
1729
1711 1754
-------------
648
olijftak
['olijftak']
1729
1728 1729
-------------
649
langerak
['langerak']
1729
1713 1735
-------------
650
beschermer
['beschermer']
1729
1709 1734
-------------
651
hottentot
['hottentot']
1729
1719 1726
-------------
652
colombo
['colombo']
1729
1717 1762
-------------
653
bouro
['bouro']
1729
1712 1719
-------------
654
speelman
['speelman']
1729
1713 1719
-------------
655
bouro
['bouro']
1729
1712 1719
-------------
656
landouw
['landouw']
1729
1708 1728
-------------
657
hottentot
['hottentot']
1729
1719 1726
-------------
658
langerak
['langerak']
1729
1713 1735
-------------
659
kleine pallas
['kleine pallas']
1785
1779 1790
-------------
660
leguaan
['leguaan']
1763
1762 1762
-------------
661
suikermaalder
['suikermaalder']
1723
1711 1754
-------------
662
haai
['haai']
1723
1722 1722
-------------
663
ontong java
['ontong java']
1723
1721 1722
-------------
664
haai
['haai']
1727
1722 1722
-------------
665
haai
['haai']
1727
1722 1722
-------------
666
hitoe
['hitoe']
1701
1701 1712
-------------

In [12]:
gzm_shiplist

['aardenhout',
 'achilles',
 'adam',
 'adam en eva',
 'adriana',
 'afrika',
 'afrikaan',
 'agnieta',
 'aletta adriana',
 'allerlande',
 'ameij',
 'amstelstroom',
 'andromeda',
 'anna',
 'anthonia',
 'anthonia dorothea',
 'appelboom',
 'arend',
 'aurora',
 'awers',
 'bagger',
 'bagger; platvis; steenbrasem',
 'bakker',
 'baloebaroe',
 'banda',
 'banka',
 'bantam',
 'barcas',
 'baros',
 'basra',
 'bastaard ',
 'batavia',
 'batavier',
 'beieren',
 'bennebroek',
 'bergwerker',
 'beschermer',
 'beverwaart',
 'beverwijk',
 'biliton',
 'blauwe berg',
 'blik',
 'bliksem',
 'boekenrode',
 'bombardier',
 'bombaria',
 'bonij',
 'boot',
 'bouro',
 'brak',
 'brandenburg',
 'breedte',
 'bruinvis',
 'buis',
 'burg',
 'cacop',
 'cacop; klipvis; witvis',
 'cadirij',
 'calpetij',
 'cananoor',
 'casuaris',
 'catharina',
 'ceilon',
 'ceram',
 'charlotte christina',
 'cheribon',
 'cicero',
 'cochin',
 'colombo',
 'constantia',
 'cornelia',
 'cornelia adriana',
 'cornelia hillegonda',
 'cornelia jacoba',
 'coupang',
 'dageraad',
 'delft',
 'den helder',
 'dijkveld',
 'dijkveld; jafnapatnam; kennermerland; manaar; visser; hammenhiel',
 'dijkveld; jafnapatnam; manaar; hamenhiel',
 'dijkveld; kennermerland',
 'doggersbank',
 'domon',
 'don quichotte',
 'doradus',
 'draak',
 'drager',
 'dubbelaar',
 'duivenbrug',
 'dwars in de weg',
 'edam',
 'eendracht',
 'eenheid',
 'eenhoorn',
 'eliphant',
 'eliphant;  landouw; dwars in de weg',
 'elisabeth',
 'ephemia',
 'erfenis',
 'europa',
 'eva',
 'eva susanna',
 'faam',
 'fortuin',
 'friesland',
 'galathea',
 'galei',
 'galjoot',
 'gamron',
 'geertruid',
 'geertruida maria',
 'geertruida susanna',
 'geinoord',
 'gerechtigheid',
 'giessenburg',
 'goa',
 'goede hoop',
 'goede trouw',
 'goes',
 'goudmijn',
 'goudvink',
 'goudvis',
 'goudzoeker',
 'grijpvogel',
 'grijze vis',
 'grote elisabeth',
 'grote schuit',
 'guinea nova',
 'haai',
 'haak',
 'haarlem',
 'haas',
 'haasje',
 'haften',
 'hagedis',
 'hammenhiel',
 'haring',
 'hasselt',
 'hector',
 'heffing',
 'hengelaar',
 'herderin',
 'hervatting',
 'hilderstein',
 'hitoe',
 'hoefijzer',
 'hoibo',
 'hoog',
 'hooiwagen',
 'hoop',
 'hoorn',
 'hoornvliet',
 'hottentot',
 'houtbos',
 'houtsnip',
 'huis te krooswijk',
 'huis te nieuwburg',
 'huis ter boede',
 'ida',
 'inaijang',
 'indermajo',
 'indigoboom',
 'isabella',
 'itershem',
 'jacob willem',
 'jafnapatnam',
 'jager',
 'jakatra',
 'jambij',
 'jan',
 'jana abang',
 'johanna',
 'johoor',
 'jonge dirk',
 'jonge petrus albertus',
 'josephina',
 'jufrouw petronella',
 'juno',
 'kaap',
 'kaars',
 'kaaskoper',
 'kalagawe',
 'kaneelboom',
 'kennermerland',
 'kerkwijk',
 'klappusboom',
 'klaverblad',
 'klein vaartuig',
 'kleine elisabeth',
 'kleine julius',
 'kleine kolibrie',
 'kleine pallas',
 'klipvis',
 'knol',
 'koffieboom',
 'kommer',
 'koningsvis',
 'kopjagt',
 'kraanpost',
 'kraanvogel',
 'krab',
 'kranke',
 'krooswijk',
 'kuiper',
 'lam',
 'lamatjang',
 'landouw',
 'landsboot',
 'langerak',
 'lapland',
 'laricque',
 'lastdrager',
 'lastloper',
 'leenvis',
 'leeuw',
 'leeuwenburg',
 'leguaan',
 'leiden',
 'lijdzaamheid',
 'lijnbaan',
 'louisa',
 'maas',
 'makreel',
 'malakse kruiser',
 'malijen',
 'manaar',
 'manaar; hammenhiel; lastdrager; hoop',
 'maria jacoba',
 'maria louisa',
 'mataram',
 'meerman',
 'meeuw',
 'meiboom',
 'meijenburg',
 'meijerend',
 'mercurius',
 'middelburg',
 'monnikendam',
 'mossel',
 'naardermeer',
 'nachtegaal',
 'nagelwanze',
 'naklegam',
 'nangel mansa',
 'nassau',
 'nederlandse maagd',
 'negapatnam',
 'negombo',
 'neira',
 'nieuw hollandia',
 'noodhulp',
 'noordster',
 'noordwijk',
 'olijftak',
 'onbeschaamdheid',
 'ongehoorzaamheid',
 'ontong java',
 'oost',
 'oostsouburg',
 'oostvoorn',
 'oppas',
 'orang oetang',
 'oranjeboom',
 'os',
 'otmij',
 'overmaas',
 'overtoom',
 'overtoom; jafnapatnam; dijkveld; manaar; hamenhiel',
 'padang',
 'pamakasaman',
 'pantjalang',
 'papegaai',
 'parel',
 'parelmoer',
 'pasarouwang',
 'patna',
 'patriot',
 'pekelharing',
 'peperboom',
 'pepertuin',
 'phoeniciër',
 'phoenix',
 'pier',
 'pijl',
 'pijnwens',
 'pimpelmees',
 'pinkstervlam',
 'pitoor',
 'platvis',
 'platvis; bagger; steenbrasem',
 'poeger',
 'posthoorn',
 'postiljon',
 'postloper',
 'potvis',
 'prins eugenius',
 'pruijen',
 'ravenburg',
 'regenboog',
 'rembang',
 'rijder',
 'rijnestein',
 'rommelpot',
 'rotte',
 'rozekrans',
 'rustenburg',
 'salpeterzoeker',
 'samarang',
 'schaapherder',
 'schelde',
 'schelvis',
 'schelvis; tangerang',
 'schiedam',
 'schildpad',
 'sibilla',
 'sint laurens',
 'sint nicolaas',
 'sleuteldrager',
 'slot ter hoge',
 'snip',
 'snoek',
 'snoeper',
 'snuffelaar',
 'solgor',
 'sourabaja',
 'sousang',
 'sousouhounang',
 'spare',
 'speelman',
 'spiering',
 'stam',
 'standvastigheid',
 'steenbok',
 'steenbrasem',
 'steenwijk',
 'ster',
 'stompneus',
 'suikermaalder',
 'sukkelaar',
 'sumanapper',
 'surseance',
 'susanna',
 'susanna catharina',
 'talmerij',
 'tanabang',
 'tangerang',
 'terschelling',
 'tienhoven',
 'tingieter',
 'tinzoeker',
 'tonijn',
 'torbaja',
 'triton',
 'uitgang',
 'unie',
 'utrecht',
 'valk',
 'veere',
 'veerman',
 'veldhuizen',
 'velserhei',
 'venhuizen',
 'venlo',
 'verlangen',
 'victoria',
 'visser',
 'vlaming',
 'vliegende vis',
 'vogelstruis',
 'volkera',
 'vondeling',
 'voorduin',
 'voorn',
 'voorzichtigheid',
 'vrede',
 'vuur',
 'waijer',
 'walvis',
 'wantrouw',
 'water',
 'waterhaler',
 'waterprauw onrust',
 'weltevreden',
 'wereld',
 'werfboot',
 'westhoven',
 'westwijk',
 'wijk op zee',
 'witvis',
 'zeelandia',
 'zeelands welvaren',
 'zeeleeuw',
 'zeelelie',
 'zeepaard',
 'zeilvis',
 'zon',
 'zuster',
 'zwaardvis',
 'zwarte arend',
 'zwerver',
 '[eiland edam]']

In [22]:
summary

          Shipname   min   max
0       aardenhout  1696  1706
1         achilles  1714  1719
2             adam  1712  1719
3      adam en eva  1718  1718
4          adriana  1736  1754
..             ...   ...   ...
398      zwaardvis  1697  1708
399   zwarte arend  1696  1696
400        zwerver  1732  1741
401  [eiland edam]  1703  1703
402     [onbekend]  1696  1747

[403 rows x 3 columns]

In [26]:
summary[((summary['max'] - summary['min']) > 40)]

            Shipname   min   max
17             arend  1724  1783
61         catharina  1742  1786
68           colombo  1717  1762
69        constantia  1727  1791
86             draak  1696  1769
132             haas  1697  1753
133           haasje  1699  1740
142         herderin  1698  1755
150             hoop  1699  1790
172          johanna  1715  1782
214          leenvis  1701  1768
215            leeuw  1697  1755
280        pepertuin  1693  1746
300          rembang  1714  1789
328            spare  1695  1787
338    suikermaalder  1711  1754
357             valk  1697  1747
374  voorzichtigheid  1715  1790
402       [onbekend]  1696  1747

In [27]:
summary[((summary['max'] - summary['min']) < 40)]

          Shipname   min   max
0       aardenhout  1696  1706
1         achilles  1714  1719
2             adam  1712  1719
3      adam en eva  1718  1718
4          adriana  1736  1754
..             ...   ...   ...
397         zuster  1736  1736
398      zwaardvis  1697  1708
399   zwarte arend  1696  1696
400        zwerver  1732  1741
401  [eiland edam]  1703  1703

[384 rows x 3 columns]

In [34]:
GLOB_ships = summary[((summary['max'] - summary['min']) < 40)]

In [35]:
GLOB_ships

          Shipname   min   max
0       aardenhout  1696  1706
1         achilles  1714  1719
2             adam  1712  1719
3      adam en eva  1718  1718
4          adriana  1736  1754
..             ...   ...   ...
397         zuster  1736  1736
398      zwaardvis  1697  1708
399   zwarte arend  1696  1696
400        zwerver  1732  1741
401  [eiland edam]  1703  1703

[384 rows x 3 columns]

In [36]:
GLOB_ships.insert(0, 'GloB_shipID', range(1857, 1857 + len(GLOB_ships)))

In [37]:
GLOB_ships

     GloB_shipID       Shipname   min   max
0           1857     aardenhout  1696  1706
1           1858       achilles  1714  1719
2           1859           adam  1712  1719
3           1860    adam en eva  1718  1718
4           1861        adriana  1736  1754
..           ...            ...   ...   ...
397         2236         zuster  1736  1736
398         2237      zwaardvis  1697  1708
399         2238   zwarte arend  1696  1696
400         2239        zwerver  1732  1741
401         2240  [eiland edam]  1703  1703

[384 rows x 4 columns]

In [39]:
GLOB_ships['GloB_shipID'] = 'GLOB_ship' + GLOB_ships['GloB_shipID'].astype(str)

<ipython-input-39-7085cbc33771>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GLOB_ships['GloB_shipID'] = 'GLOB_ship' + GLOB_ships['GloB_shipID'].astype(str)

In [40]:
GLOB_ships

       GloB_shipID       Shipname   min   max
0    GLOB_ship1857     aardenhout  1696  1706
1    GLOB_ship1858       achilles  1714  1719
2    GLOB_ship1859           adam  1712  1719
3    GLOB_ship1860    adam en eva  1718  1718
4    GLOB_ship1861        adriana  1736  1754
..             ...            ...   ...   ...
397  GLOB_ship2236         zuster  1736  1736
398  GLOB_ship2237      zwaardvis  1697  1708
399  GLOB_ship2238   zwarte arend  1696  1696
400  GLOB_ship2239        zwerver  1732  1741
401  GLOB_ship2240  [eiland edam]  1703  1703

[384 rows x 4 columns]

In [52]:
GLOB_ships.to_excel('Glob_ships.xlsx')

In [45]:
das = pd.ExcelFile('das.xlsx')
das_ships = das.parse('shipNameVariant')
das_ships = das_ships.set_index('shipNameVariantID')
das_voyages = das.parse('das_voyage')
das_voyages = das_voyages.set_index('voyId')

In [46]:
das_ships

,shipID,shipNameVariant,shipNameVariantRemark
shipNameVariantID,,,
DAS_snv0001,DAS_ship0001,'s Heer Arendskerke,NaN
DAS_snv0002,DAS_ship0002,'s Lands Welvaren,NaN
DAS_snv0003,DAS_ship0003,'s-Graveland,NaN
DAS_snv0004,DAS_ship0004,'s-Graveland,NaN
DAS_snv0005,DAS_ship0005,'s-Gravenhage,NaN
...,...,...,...
DAS_snv1893,DAS_ship1852,Schaapherder,NaN
DAS_snv1894,DAS_ship1853,Senhor De Bonfim E Sancta Maria,NaN
DAS_snv1895,DAS_ship1854,Toevalligheid,NaN
DAS_snv1896,DAS_ship1855,Batavier,NaN
DAS_snv1897,DAS_ship1856,Herstelder,NaN

In [47]:
das_voyages

,url,voyNumberDAS,heenreis,terugreis,shipID,shipName,voyMasterID,voyMasterRemark,voyChamberID,voyDepartureEDTF,...,voyCapeDepartureEDTF_remark,voyArrivalDateEDTF,voyArrivalDateEDTF_remark,voyArrivalPlaceID,voyInvoiceValue,voyChamber2ID,voyParticulars,voyCorrespondingNumber,voyRGPDeel,voymaster_VOCOPVid
voyId,,,,,,,,,,,,,,,,,,,,,
91055,http://resources.huygens.knaw.nl/das/detailVoy...,0001.1,1,0,DAS_ship0054,DAS_snv0056,das_mas2328,NaN,NaN,1595-04-02,...,NaN,1596-06-06,NaN,DAS_pl024,NaN,NaN,Equipped (0001-0004) by the Compagnie van Verr...,NaN,166,NaN
91056,http://resources.huygens.knaw.nl/das/detailVoy...,0002.1,1,0,DAS_ship0337,DAS_snv0348,das_mas1789,NaN,NaN,1595-04-02,...,NaN,1596-06-06,NaN,DAS_pl024,NaN,NaN,Mau became master of the HOLLANDIA on 26-10-15...,5001,166,NaN
91057,http://resources.huygens.knaw.nl/das/detailVoy...,0003.1,1,0,DAS_ship0624,DAS_snv0643,das_mas1589,NaN,NaN,1595-04-02,...,NaN,1596-06-06,NaN,DAS_pl024,NaN,NaN,Jan Dignumsz. died on 29-05-1595 and Mau was h...,5002,166,NaN
91058,http://resources.huygens.knaw.nl/das/detailVoy...,0004.1,1,0,DAS_ship0953,DAS_snv0981,das_mas1868,NaN,NaN,1595-04-02,...,NaN,1596-06-06,NaN,DAS_pl024,NaN,NaN,Jan Jansz. died on 25-12-1596 and Hendrik Jans...,5003,166,NaN
91059,http://resources.huygens.knaw.nl/das/detailVoy...,0005.1,1,0,DAS_ship0857,DAS_snv0882,das_mas2641,NaN,NaN,1598-03-25,...,NaN,1599-03,NaN,DAS_pl006,NaN,NaN,Fleet (0005-0007) equipped by the Compagnie Te...,5010,166,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99180,http://resources.huygens.knaw.nl/das/detailVoy...,8397.1,0,1,DAS_ship1809,DAS_snv1850,das_mas2139,NaN,DAS_cham006,1795,...,NaN,1795-09-18,NaN,DAS_pl068,365.373,DAS_cham006,NaN,4772,167,NaN
99181,http://resources.huygens.knaw.nl/das/detailVoy...,8398.2,0,1,DAS_ship0967,DAS_snv0995,das_mas1999,NaN,DAS_cham001,1795,...,NaN,NaN,NaN,NaN,NaN,NaN,Date of arrival at the Cape unknown. On 18-05-...,4674,167,NaN
99182,http://resources.huygens.knaw.nl/das/detailVoy...,8399.1,0,1,DAS_ship0739,DAS_snv0758,das_mas1560,NaN,DAS_cham006,1795,...,NaN,NaN,NaN,NaN,50.232,DAS_cham006,Almost all data concerning this homeward-bound...,4774,167,NaN
99183,http://resources.huygens.knaw.nl/das/detailVoy...,8400.1,0,1,DAS_ship0915,DAS_snv0942,das_mas2665,NaN,DAS_cham001,1795,...,NaN,NaN,NaN,NaN,85.711,DAS_cham001,Almost all data concerning this homeward-bound...,4777,167,NaN
99184,http://resources.huygens.knaw.nl/das/detailVoy...,8401.1,0,1,DAS_ship1516,DAS_snv1554,NaN,NaN,DAS_cham001,1795,...,NaN,NaN,NaN,NaN,106.435,DAS_cham001,Almost all data concerning this homeward-bound...,4778,167,NaN

In [48]:
# Now I want a list of individual ships from DAS and the years between which they were employed
# Converting the date to datetime is not possible, since many voyages took place before 1677 (out of bounds)
# This means we lose vectorization advantages anyway, so I'll generate a dataframe using a Python loop 

# Create an empty list to hold the data on ships and dates
das_ship_dates = []

# Populate the list with data from DAS
for voyage in das_voyages.index:
    current_ship_id = das_voyages.loc[voyage, 'shipID']
    current_ship_name_id = das_voyages.loc[voyage, 'shipName']
    current_ship_departure = das_voyages.loc[voyage, 'voyDepartureEDTF']
    current_ship_arrival = das_voyages.loc[voyage, 'voyArrivalDateEDTF']
    current_ship_name = das_ships.loc[current_ship_name_id, 'shipNameVariant']
    
    # Convert dates to 4 digits (datetime not possible w/o workarounds)
    current_ship_departure = str(current_ship_departure)
    current_ship_departure = current_ship_departure[:4]
    current_ship_arrival = str(current_ship_arrival)
    current_ship_arrival = current_ship_arrival[:4]

    # Construct a list with data on this voyage
    this_voyage = (voyage, current_ship_name, current_ship_id, current_ship_name_id, current_ship_departure, current_ship_arrival)
    
    # Append that list to the aforementioned list (of lists)
    das_ship_dates.append(this_voyage)
    
# Create a Pandas dataframe from the list of lists
fulldata = pd.DataFrame.from_records(das_ship_dates, columns=['DasID', 'Shipname', 'DasShipID', 'DasShipNameVariant', 'Startyear', 'Endyear'])
fulldata = fulldata.set_index('DasID')

# Convert the yearcolumns to numeric values (they include some messed up data)
fulldata['Startyear'] = pd.to_numeric(fulldata['Startyear'], errors='coerce')
fulldata['Endyear'] = pd.to_numeric(fulldata['Endyear'], errors='coerce')

# Now we can drop NaNs (error coercion made these NaN)
# And subsequently convert from float to int (due to messed up data, to_numeric couldn't do this)

fulldata['Startyear'] = fulldata['Startyear'].astype(pd.Int32Dtype())
fulldata['Endyear'] = fulldata['Endyear'].astype(pd.Int32Dtype())

In [49]:
# We now have all the data to make a dataframe with: DAS IDs, shipnames, first year the ship was active,
# and last year the ship was active (on intercontinental voyages)
# Caveat: NaN-values are excluded
summarydas = fulldata.groupby(['DasShipNameVariant']).agg({'Shipname':'last', 'DasShipID':'last', 'Startyear':'min', 'Endyear':'max'})
summarydas

,Shipname,DasShipID,Startyear,Endyear
DasShipNameVariant,,,,
DAS_snv0001,'s Heer Arendskerke,DAS_ship0001,1725,1742
DAS_snv0002,'s Lands Welvaren,DAS_ship0002,1763,1773
DAS_snv0003,'s-Graveland,DAS_ship0003,1659,1660
DAS_snv0004,'s-Graveland,DAS_ship0004,1723,1726
DAS_snv0005,'s-Gravenhage,DAS_ship0005,1628,1635
...,...,...,...,...
DAS_snv1893,Schaapherder,DAS_ship1852,1690,1693
DAS_snv1894,Senhor De Bonfim E Sancta Maria,DAS_ship1853,1782,<NA>
DAS_snv1895,Toevalligheid,DAS_ship1854,1745,1745
DAS_snv1896,Batavier,DAS_ship1855,1736,1758
DAS_snv1897,Herstelder,DAS_ship1856,1772,1781

In [51]:
summarydas.to_excel('summarydas.xlsx')

In [13]:
len(gzm_shiplist)

402